[package]
name = "bc-api-client"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
futures = { version = "0.3", features = ["executor"] }
serde_json = { version = "1" }
