name: code quality check

on:
  push:
    branches: [main]
    pull_request:

jobs:
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: linting with clippy
        run: cargo clippy --tests --examples
      - name: linting with clippy with all features enabled
        run: cargo clippy --tests --examples --all-features
  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: enforce formatting
        run: cargo fmt --check
  test:
    name: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/postgres
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: run tests with all features enabled
        run: cargo test --release --all-features
